### ISSUE TITLE
SQL or NoSQL

### ISSUE THREAD

**Issue by corez92** [JessicaNgo/TeleGiphy#27]
I remember someone saying we'd use MongoDB, yet at https://github.com/JessicaNgo/TeleGiphy/issues/25 it seems a regular schema was designed? I'm not sure of the compatibility of mongo with Django. A quick Google search returned this for mongo:

https://django-mongodb-engine.readthedocs.io/en/latest/

This is important for the scope as well.

**Comment by zapplecat** [comment]
@Mester mentioned that NoSQL is probably going to be a difficult fit with django off handedly. I think since django natively supports SQL, that'll be the slightly easier option (and that's why I designed normal models). What you have linked looks easy enough, but doesn't seem like the project has been updated for more than a year, so I would be wary about using it without reading into it.

**Comment by Mester** [comment]
Honestly, with Django, I don't really see any reason for using mongodb. Since it feels like almost the same since you don't really do any sql queries manually or anything. If you have some great reason for it, speak up :P

**Comment by corez92** [comment]
Nope, actually I liked working with MongoDB but didn't have any preference for this project. Let's not make things difficult though, so I think MySQL would be the best option then. Or can we use SQLite for production purposes? Then there's also PostgreSQL

**Comment by Mester** [comment]
I think for such a tiny app/userbase sqlite should be fine. But I know practically nothing about databases so I might be wrong. The program itself won't look any different anyway regardless of which sql, it should just be some changes in the settings

**Comment by zapplecat** [comment]
I'm going to call this issue solved and that we're going with sqlite.
