### ISSUE TITLE
Inbetween rounds/waiting for next player view

### ISSUE THREAD

**Issue by Mester** [JessicaNgo/TeleGiphy#66]
Part of #64 (This should've been part of hotseat too actually)

**Comment by corez92** [comment]
Not sure what you mean by this. In multi the players are always entering text or doing something and in hotseat it's the same someone is always busy filling in their guess/text.

Only for multi is where I can forsee someone who sends their gif to the next person where they dont have anything to do, this is where the 10 seconds limit come into play, so they just wait for the timer to run out

**Comment by Mester** [comment]
In hotseat it would be a screen that says something like "it's the next player's turn, click to continue"

What do you mean by that limit? People have a time limit to enter their gif?

**Comment by corez92** [comment]
You can do that in hotseat of course, but is it crucial? No, people will send the device over to the next person anyway and we can name the person who has to play each time on the screen so people know what's up. Again, hotseat shouldn't be and isn't the focus.

There were two ways to keep the game moving: 10 second limit (or more/less) or constant refresh by user (dangerous, might hold up game if one person doesnt refresh). There are two cases (for multi):
- A person passes a gif before the time limit is over. The person has to wait for the time to be over for all other players, so here you can put a in-game wait page. 
- A person doesn't fill in anything, "" is passed, this still works with the giphy api but produces a random gif. Someone can leave their keyboard for example.

The time limit is important so that everyone is moving along at the same time.

**Comment by JessicaNgo** [comment]
In multiplayer: 
for simplicity lets just check if it is the player's turn: 
if it is: 
redirect them to a page similar to the hotseat_gameplay.html

if it is not: 
have a basic "multi_waiting.html" where its basically like "its another players turn right now", 
with a button to go to attempt to go to gameplay (page simliar to the hotseat_gameplay.html),
and if it's still not the players turn, redirects them to the multi_waiting.html again.

**Comment by zapplecat** [comment]
I can see this being in hotseat. Basically a screen to make sure the new player actually gets situated before they start. It would be especially good if we're actually enforcing time limits.

For multiplayer @JessicaNgo makes sense. Also if it's actually multiplayer, with everyone with their own active "game rounds" running, then the "multi_waiting.html" is especially important.

In the chat I had mentioned that there's 2 things we can do with the waiting.html (assuming it refreshes itself every so often):
1. List the players that haven't gone yet
2. Have a mini-game where players can just press a doge button, and at gameover, it shows up how many times people pressed doge.

**Comment by corez92** [comment]
see #85
