### ISSUE TITLE
Reminder: Tests... tests and more tests

### ISSUE THREAD

**Issue by JessicaNgo** [JessicaNgo/TeleGiphy#8]
We should include tests as a first thing to write for each function/issue/milestone!

**Comment by Mester** [comment]
So you want us to do TDD?

**Comment by corez92** [comment]
TDD? test driven development? I think that would be a good practice.

**Comment by Mester** [comment]
Well a bit late for TDD at this point :P But could still write tests first if you want.

**Comment by corez92** [comment]
I think what she meant was, when you write some function, you should also write the corresponding test case to see if it works and for later if we do refactoring to check if it still works. Basically all those annoying tests we had for the projects, we should be including those when coding. Idk what TDD is otherwise, I just googled what the abbreviation meant honestly.

**Comment by Mester** [comment]
Since she mentioned "first" I was wondering if she meant to write tests first, or functionality first. Anyway, this is a very strange issue to have :P. Should be somewhere else, in slack or scope or coding guidelines or workflow or I dunno.

TDD is a long story, not gonna go through it here. I could explain on slack if you're interested.

**Comment by corez92** [comment]
Yeah this is meta issue..not even an issue just a general thing and should definitely be in a one of those docs. I'm also just now discovering some shizzle on GitHub like the milestones pages.

**Comment by taqpol** [comment]
@corez92, TDD means that your unit tests are written before you start writing the actual code. Writing alongside your test cases is not TDD.

Also, I'm not going to watch this project anymore. I'm getting too many emails.

**Comment by corez92** [comment]
Okay, then what's writing on the side like that called. Idk I still have to dive into writing tests and etc.

Also, who are you lol @taqpol
